
CREATE DATABASE BOOK_RECOMMENDATION

USE BOOK_RECOMMENDATION

DROP TABLE BOOKS
CREATE TABLE BOOKS(
	title NVARCHAR(600),
	link NVARCHAR(600),
    genre NVARCHAR(600),
    author NVARCHAR(255),
    description NVARCHAR(4000)
)